cabal-version: 3.0
name: SenaVN
version:
  2.0.0.0

homepage:
  https://vn.himeno-sena.com

license:
  GPL-3.0-only

author:
  ArimuraSena

maintainer: biyuehuya@gmail.com
build-type: Simple
extra-doc-files:
  CHANGELOG.md

common shared-properties
  ghc-options: -Wall
  default-language: Haskell2010
  default-extensions:
    DeriveAnyClass
    DeriveGeneric
    DuplicateRecordFields
    OverloadedRecordDot
    OverloadedStrings

  build-depends:
    aeson,
    aeson-pretty,
    base ^>=4.19,
    bytestring,
    directory,
    filepath,
    haskeline,
    optparse-applicative,
    prettyprinter,
    prettyprinter-ansi-terminal,
    process,
    random,
    req,
    sqlite-simple,
    template-haskell,
    temporary,
    text,
    time,
    transformers,

library
  import: shared-properties
  hs-source-dirs: src
  exposed-modules:
    SenaVN
    SenaVN.Api
    SenaVN.Classes
    SenaVN.Command
    SenaVN.Core
    SenaVN.DB
    SenaVN.Handler
    SenaVN.Pretty
    SenaVN.Session
    SenaVN.Types
    SenaVN.Utils

executable SenaVN
  import: shared-properties
  main-is: Main.hs
  hs-source-dirs: app
  build-depends: SenaVN