name: Build

on:
  push:
    branches:
      - main
    tags:
      - '!v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install frontend dependencies
        run: npm install --frozen-lockfile

      - name: Build project
        run: npx pnpm tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-latest-gal-keeper
          path: src-tauri/target/release/Nanno.exe
